apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/parthivrmenon/moonpie
    targetRevision: HEAD
    path: apps/mongo
  destination: 
    server: https://kubernetes.default.svc
    namespace: moonpie-infra

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true